import type { AccessLog, Alert, Device, Member, Role } from '../../types';

export const mockDevices: Device[] = [
  {
    id: 'SV-001',
    name: 'Main Lobby',
    location: 'Main Lobby',
    mac: 'A0:B1:C2:D3',
    ip: '192.168.1.42',
    firmware: 'v2.4.1',
    status: 'online',
    lockState: 'locked',
    signal: -45,
    signalLabel: 'Strong',
    battery: 92,
    lastHeartbeat: '2s ago',
    lastSeen: 'Online',
  },
  {
    id: 'SV-004',
    name: 'Server Room',
    location: 'Server Room',
    mac: 'E4:F5:A1:B2',
    ip: '192.168.1.44',
    firmware: 'v2.4.1',
    status: 'online',
    lockState: 'unlocked',
    signal: -62,
    signalLabel: 'Moderate',
    battery: 45,
    lastHeartbeat: '5s ago',
    lastSeen: 'Online',
  },
  {
    id: 'SV-012',
    name: 'Storage C',
    location: 'Storage C',
    mac: 'C3:D4:E5:F6',
    ip: '192.168.1.56',
    firmware: 'v2.3.9',
    status: 'offline',
    lockState: 'locked',
    signal: -120,
    signalLabel: 'No Signal',
    battery: 12,
    lastHeartbeat: '2h ago',
    lastSeen: 'Offline',
  },
  {
    id: 'SV-009',
    name: 'Warehouse B',
    location: 'Warehouse B',
    mac: 'AA:BB:CC:DD',
    ip: '192.168.1.99',
    firmware: 'v2.4.1',
    status: 'online',
    lockState: 'locked',
    signal: -58,
    signalLabel: 'Good',
    battery: 78,
    lastHeartbeat: '12s ago',
    lastSeen: 'Online',
  },
];

export const mockAccessLogs: AccessLog[] = [
  {
    id: 'log-1',
    deviceId: 'SV-001',
    timeLabel: '10:42:01 AM',
    event: 'Unlock Success',
    method: 'Biometric (Face)',
    user: 'S. Jenkins',
    status: 'success',
    relativeTime: '1m',
  },
  {
    id: 'log-2',
    deviceId: 'SV-004',
    timeLabel: '08:15:33 AM',
    event: 'Unlock Success',
    method: 'Mobile App (Remote)',
    user: 'Admin',
    status: 'success',
    relativeTime: '2h',
  },
  {
    id: 'log-3',
    deviceId: 'SV-012',
    timeLabel: 'Yesterday',
    event: 'Auth Failed',
    method: 'PIN Pad',
    user: 'Unknown',
    status: 'failed',
    relativeTime: '4h',
  },
  {
    id: 'log-4',
    deviceId: 'SV-009',
    timeLabel: 'Today',
    event: 'Tamper Detected',
    method: 'Sensor Trip',
    user: 'System',
    status: 'warning',
    relativeTime: '4h',
  },
];

export const dashboardEvents: AccessLog[] = [
  {
    id: 'evt-1',
    deviceId: 'SV-004',
    timeLabel: '1m',
    event: 'Bio-Auth Success',
    method: 'User: Admin / SV-004',
    user: 'Admin',
    status: 'success',
  },
  {
    id: 'evt-2',
    deviceId: 'SV-012',
    timeLabel: '2h',
    event: 'PIN Unlock',
    method: 'Offline Mode / SV-012',
    user: 'SysOperator',
    status: 'warning',
  },
  {
    id: 'evt-3',
    deviceId: 'SV-009',
    timeLabel: '4h',
    event: 'Tamper Detected',
    method: 'Sensor Trip / SV-009',
    user: 'System',
    status: 'failed',
  },
];

export const mockMembers: Member[] = [
  {
    id: 'member-1',
    name: 'SysOperator (You)',
    email: 'sysop@smartvault.io',
    initials: 'SO',
    role: 'owner',
    added: 'Jan 12, 2024',
    accent: 'bg-emerald-500 text-white',
  },
  {
    id: 'member-2',
    name: 'Sarah Jenkins',
    email: 's.jenkins@smartvault.io',
    initials: 'SJ',
    role: 'admin',
    added: 'Feb 28, 2024',
    accent: 'bg-zinc-800 text-zinc-300 border border-white/10',
  },
  {
    id: 'member-3',
    name: 'David Klein',
    email: 'd.klein@smartvault.io',
    initials: 'DK',
    role: 'editor',
    added: 'Mar 10, 2024',
    accent: 'bg-zinc-800 text-zinc-300 border border-white/10',
  },
  {
    id: 'member-4',
    name: 'Guest Auditor',
    email: 'auditor@external.com',
    initials: 'GU',
    role: 'viewer',
    added: 'Yesterday',
    accent: 'bg-zinc-900 text-zinc-600 border border-white/5',
  },
];

export const mockRoles: Role[] = [
  {
    id: 'owner',
    label: 'Owner',
    description: 'Full control. Can transfer ownership and delete vault.',
  },
  {
    id: 'admin',
    label: 'Admin',
    description: 'Can manage members, change roles, and edit vault content.',
  },
  {
    id: 'editor',
    label: 'Editor',
    description: 'Can edit items. Cannot manage access.',
  },
  {
    id: 'viewer',
    label: 'Viewer',
    description: 'Read-only access to vault contents.',
  },
];

export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    deviceId: 'SV-009',
    title: 'Critical Security Event',
    message: 'Device SV-009 (Warehouse B) reported accelerometer spike.',
    severity: 'critical',
  },
];
